title: Learning the Basics of JavaScript (Bit Project + Twilio)
description: >-
  This learning lab course is intended for the purpose of Bit Project's bootcamp
  with Twilio on JavaScript.
template:
  repo: javascript-template
  name: twilio-javascript-folder
before:
  - type: createIssue
    title: Week 0
    body: 0.0-welcome.md
steps:
  - title: 'Week 0: Welcome!'
    description: Week 0 Description
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: 0.0-response.md
        issue: 1
      - type: createIssue
        title: Week 1
        body: 1.1-fizzbuzz.md
        
  - title: 'Week 1: Fizzbuzz'
    description: Week 1 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: 1.2-github.md
        
  - title: 'Week 1: Github'
    description: Week 1 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: 1.3-terminal.md
        
  - title: 'Week 1: Terminal'
    description: Week 1 Description
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: 0.0-response.md
      - type: createIssue
        title: Week 2
        body: 2.1-romancalc.md
        
  - title: 'Week 2: Roman Calc (p1)'
    description: Week 2 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 2.2-romancalc.md
        
  - title: 'Week 2: Roman Calc (p2)'
    description: Week 2 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 2.3-romancalc.md
        
  - title: 'Week 2: Roman Calc (p3)'
    description: Week 2 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 2.4-romancalc.md
        
  - title: 'Week 2: Roman Calc (p4)'
    description: Week 2 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 2.5-romancalc.md
        
  - title: 'Week 3: Recursion Intro'
    description: Week 2 Description
    event: issues.closed
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 0.0-response.md
      - type: createIssue
        title: Week 3
        body: 3.1-recursion-intro.md
        
  - title: 'Week 3: Javascript Canvas'
    description: Week 3 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 3.2-javascriptcanvas.md
        
  - title: 'Week 3: Recursion Example'
    description: Week 3 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 3.3recursionexample.md
        
  - title: 'Week 3: Creating Art'
    description: Week 3 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 3.4-creatingart.md
        
  - title: 'Week 4: Final Projects (pt1)'
    description: Week 3 Description
    event: issues.closed
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 0.0-response.md
      - type: createIssue
        title: Week 4
        body: 4.1-project.md
        
  - title: 'Week 4: Final Projects (pt2)'
    description: Week 4 Description
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: respond
        with: 0.0-done.md
      - type: closeIssue
        issue: 5
tags:
  - Twilio
  - Twilio Quest
  - Bit Project
  - Bit Camp
  - JavaScript
